(in-package :clml.extras.docs)

(defun generate-api-docs ()
  "Generates Org API documentation in the *clml.extras/docs/api* directory from loaded packages for
CLML for packages matching the following prefix patterns:
  +^clml[.]

  Documentation is in the form of Org files where one Org file per package is placed in
  *docs/api*.  A package index file containing Org INCLUDE directives that include Org
  placed generated in *clml/docs/api/index.org*.

  The CLML.extras users manual includes the generated API documentation file index.org,
  HTML documentation can then be generated by opening the clml-manual.org file in Emacs
  and entering the Org mode export mode with ~C-c C-e~ and selecting file export with ~h h~ 
"
  (make-docs (find-packages '("^clml[.]r-datasets" "^clml[.]ana[.]plotting" "clml[.]cl-plplot"))  :base-package-name 'clml.extras)
  )
