   
** Usage
This library contains the following extensions:
  +clml.ana.plotting : Compatibility layer between CLML and CL-ANA
    CL-ANA is a gnuplot wrapper and provides complimentary functionality to
    CLML. of particular not is the lispy gnuplot wrapper and
    histograms.
  +clml.r-datasets
    Provides access to datasets included with the R programming
    language as CLML datasets.

*** CLML.ANA

Below demonstrates using CL-ANA's gluplot with CLML datasets and using
data from CLML datasets to feed CL-ANA's histograms.
#+INCLUDE: "./sample/cl-ana-plotting.org"

*** CLML.R-DATASETS

#+INCLUDE: "./sample/r-datasets.org"

** Building Documentation

  CLML.EXRTAS uses the a modified version of the CLOD (used in CLML) package for it's
  dcumentation system. Specific details of using clod can be found
  most easily in the [[http://quickdocs.org/clod/api][clod]] api documentation] at [[http://][quickdocs]]

#+BEGIN_SRC lisp
(ql:quickload :clml.extras.docs :verbose t)
(in-package :clml.extras)
(clml.extras.docs:generate-clml-api-docs)
#+END_SRC
  Documentation is in the form of Org files where one Org file per package is placed in
  *docs/api*.  A package index file containing Org INCLUDE
  directives that include 
  Org files generated by the form *generate-api-docs* are  placed
  in *docs/api/index.org*.

  The README.md file is generated by the org-mode export function.
  Which can be done by opening the README.org file in emacs and
  entering org-mode and using the export function ~C-c C-e~ and
  selecting the markdown export option as shown below.
#+BEGIN_SRC lisp
  M-x org-md-export-as-markdown
  C-x-C-w README.md
#+END_SRC
  The CMLM manual and API documentation can be exported to the desired 
  format by opening the docs/clml-manual.org and using the org-mode
  export ~C-c C-e~ cord.

** API Documentation
#+INCLUDE: "./api/index.org" :minlevel 1
